### ISSUE TITLE
Open Smart Grid Platform impression

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#142]
Hello @manthanrtilva and @naguirre, I saw some in interest in our project. I was wondering: What is your impression of the Open Smart Grid Platform? Could it be usefull?

**Comment by manthanrtilva** [comment]
Hi,

I am exploring about IEC 61850, for Solar based Microgrid system, and I
come across this platform.

For now this may not useful for us, but in future project I will evaluate
this.



-Regards.
----------------------------------------
Manthan TIlva.
Mob.:+91 88 66 751781
