### ISSUE TITLE
add Java JDBC driver to the tutorial

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#16]
https://github.com/OSGP/Config/issues/6

@kevinsmeets 
Do you agree with marius-stanasel about his suggestion?

**Comment by kevinsmeets** [comment]
No not really: the JDBC driver is added by puppet when following the installation script steps, so there should not be a need to do this manually. When people are going to do manual things, we should point the puppet steps out to them as those steps document everything which is needed to get up and running.

**Comment by Sander3003** [comment]
Thanks for the information. I will make a new issue.
