### ISSUE TITLE
SoapUI Test from documentation not working

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [OSGP/Documentation#184]
While trying to run the [first SoapUI (AddManufacturer function) test from the documentation](https://github.com/OSGP/Documentation/blob/development/Userguide/Installation/testOSGP.md) I get this error
`Tue Mar 13 07:34:54 PYST 2018:ERROR:An error occurred [URI does not specify a valid host name: https:///osgp-adapter-ws-core/common/firmwareManagementService/], see error log for details`

**Comment by ElkanRoelen** [comment]
The endpoint should probably be: https://localhost/osgp-adapter-ws-core/common/firmwareManagementService/ if installed local.
Good luck!

**Comment by Karlheinzniebuhr** [comment]
Thanks that worked. Still getting errors though
```
Tue Mar 13 09:07:14 PYST 2018:ERROR:Could not load keystore/truststore
Tue Mar 13 09:07:14 PYST 2018:ERROR:java.io.FileNotFoundException: /home/dev/Sources/OSGP/Integration-Tests/platform-tests/certificates/test-org.pfx (No such file or directory)
```
