### ISSUE TITLE
Vagrant machine user is not exist

### ISSUE THREAD

**Issue by ahmedsoliman64** [OSGP/Documentation#194]
the dev user on the vagrant machine not exist

**Comment by Sander3003** [comment]
Thank you for the report, the developers are currently busy, they will reply later.

**Comment by rlemmers** [comment]
What have you done to check this? Which users do you have in the /home folder of the created image? Were you able to log on using user _dev_?

We use _vagrant_ mainly for the roll out. The roll out places all kinds of stuff in /home/dev. After the roll out, we use _dev_ to use the VM.

I just rolled out the environment using Vagrant on my laptop (which runs on Windows 8). After the run, I did have users for both _vagrant_ and _dev_. By default, it will use _dev_ to log on. I logged out the _dev_ and the logged on _vagrant_ (password "vagrant"), which was successful.

What I did notice in the roll out: the final step is a restart of the created VM. This was done with a delay of about a minute. During that minute, it shows the log on screen and logging on using _dev_ failed at that time. After the restart was actually done, everything was fine.
