### ISSUE TITLE
Simulating the Infrastructure

### ISSUE THREAD

**Issue by sarah225** [OSGP/Documentation#204]
Hi,
I have several questions. Suppose we want to create an AMI. 

1. Is it possible to add some real smart meters (which uses DLMS protocol)?
2. Or, is there something available for simulating this kind of smart meter?
3. Is SoapUI able to act as a real headend and send and receives packets and commands with DLMS TCP? 
4. And finally, is it possible to capture transferred packets with something like Wireshark?

Regards,
Sarah

**Comment by Sander3003** [comment]
@sarah225 feel free to help us improve the documentation related to your questions. This could benefit all new/interested users.

**Comment by sarah225** [comment]
> 1. If you have a real smart meter available and know it's security configuration (authentication and encryption keys), you would be able to add it to OSGP.
> 2. We currently do not support an open source device simulator. However, you could try using the Fraunhofer OpenMuc jDlms library to create one. (See https://www.openmuc.org/dlms-cosem/)
> 3. OSGP exposes its functionality through SOAP web services. OSGP will translate the SOAP requests into DLMS for device communication. Therefore you could use SoapUI to communicate with smart meters using OSGP.
> 4. Sure, you could capture the packets using Wireshark. However most packets will probably contain encrypted data and therefore will not be very readable.

Thanks a lot @smvdheijden for your response, I appreciate it a lot.

**Comment by sarah225** [comment]
> @sarah225 feel free to help us improve the documentation related to your questions. This could benefit all new/interested users.

Sure, I'll let you know if I have any suggestion.
