### ISSUE TITLE
Documentation Link for OSGP Not working.

### ISSUE THREAD

**Issue by Sanu153** [OSGP/Documentation#212]
Documentation Link for OSGP Not working and throwing this error **403 Forbidden** 

> http://documentation.opensmartgridplatform.org/

Kindly help me to resolve the issue. The screenshot is attached below.

![Screenshot from 2019-09-23 16-21-02](https://user-images.githubusercontent.com/19161632/65420196-2d2fc000-de1e-11e9-8963-cf39c97bbb8f.png)

**Comment by Sander3003** [comment]
Thanks for your report, I have the same experience here.

**Comment by Sander3003** [comment]
Workaround: https://ci.opensmartgridplatform.org/job/OSGP_Documentation_development/lastSuccessfulBuild/artifact/

**Comment by robindenadel** [comment]
documentation is back online

**Comment by Sanu153** [comment]
Thank you for your help and time.

I'm closing this issue and will be raising another in case I encounter any.
