### ISSUE TITLE
lighting sensor

### ISSUE THREAD

**Issue by winy57** [OSGP/Documentation#220]
Hello,

I have a question about the use of schedules. In the example given here http://documentation.opensmartgridplatform.org/Protocols/OSLP/v0.6.1/SetSchedule.html, you use a lighting sensor. 
This sensor does not communicate directly with the SSLD, but with the platform which then sends a SetTransition to the SSLD, right? Or this sensor is included on the SSLD ??

Thanks,
Mickael

**Comment by rtusveld** [comment]
Hello Mickael,

you are right, the sensor doesn't communicate directly with the SSLD. It will communicate with the GXF platform and then send the SetTransition message to the SSLD. Of course it's also posible to add a sensor to a SSLD, but this will be a more costly solution and the SSLD is in our case installed in a closed space with no daylight available. For us the central solution switching a lot of SSLD's on the same time, based on a single lighting sensor seemed the most logical solution. 

If you have any additional questions, let us know!

Robert

**Comment by winy57** [comment]
Hello Robert,

Thank you for your answer which confirms my understanding. 
Our wish would indeed be to have a brightness sensor on each source station, and not on each SSLD. We currently have a Lumandar but this one is not connected to the SI but simply sends a signal to the power grid.
Is the sensor you use available on the market, or is it a homemade and protected design?

Thanks,
Mickael

**Comment by rtusveld** [comment]
Hi Mickael,

Yes the sensor has been developed by Elster, part of Honywell. I have a flyer of the SSLD that we are using at Alliander. See [FPLS und LCB760 Flyer Entwurf 0.2.pdf](https://github.com/OSGP/Documentation/files/4608009/FPLS.und.LCB760.Flyer.Entwurf.0.2.pdf)

Please let me know if the information is suitable for you!

Robert

**Comment by winy57** [comment]
Hi Robert,

Thank you for this documentation! I know the LCB760 box, or rather its successor which integrates the modem, I am already in contact with WM Systems. But the brightness sensor is not integrated in this box. It is thus Elster which manufactures it? Do you have a reference of this brightness sensor? 

Thanks,
Mickael

**Comment by rtusveld** [comment]
I'm not familiar with these brightness sensors. For GXF these are hidden behind a RTU (IEC 61850), which translates to sensor information into a boolean which indicates whether it is light or dark for a specific lightmeasurement device. 

Best regards,
Robert
