### ISSUE TITLE
OSGP Vagrant installation issues

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#221]
Here is a list of problems we encountered during the first OSGP installation which was done according to the official [installation guide](https://documentation.opensmartgridplatform.org/Userguide/Installation/Setup-VM-Vagrant.html)
1. Git clone fails with error: inflate: data stream error (incorrect data check)
2. Eclipse version is too old: https://bugs.eclipse.org/bugs/show_bug.cgi?id=515859

Here is a list of workarounds that have been applied in order to solve the aforementioned problems.
1. Update [Vagrantfile](https://github.com/OSGP/Config/blob/915b0eaca2dbf028c15cd307ef2038acce5fdcc9/vagrant/Vagrantfile#L33) and [clone-repositories.pp](https://github.com/OSGP/Config/blob/915b0eaca2dbf028c15cd307ef2038acce5fdcc9/puppet/manifests/clone-repositories.pp#L6-L16): use GIT protocol instead of HTTPS
2. Update [eclipse.pp](https://github.com/OSGP/Config/blob/915b0eaca2dbf028c15cd307ef2038acce5fdcc9/puppet/manifests/eclipse.pp#L6): use Eclipse Oxygen 3a release

Additionally, while trying to setup SoapUI we noticed that it is not possible to retrieve osgp-ws-microgrids XSD files, an HTTP 405 error occurs.
```
curl -s -o /dev/null -w '%{http_code}' https://localhost/osgp-adapter-ws-microgrids/wsdl/microgrids/adHocManagementService/schemas/adhocmanagement.xsd
405
```
WSDL file can be retrieved without any problems
```
curl -s -o /dev/null -w '%{http_code}' https://localhost/osgp-adapter-ws-microgrids/wsdl/microgrids/adHocManagementService/MicrogridsAdHocManagement.wsdl
200
```
As a workaround, WSDL can be loaded from the filesystem:
```
file:/home/dev/Sources/OSGP/open-smart-grid-platform/osgp/shared/osgp-ws-microgrids/src/main/resources/MicrogridsAdHocManagement.wsdl
```

**Comment by kevinsmeets** [comment]
Thank you for your suggestions, ThE-MaRaC. 

I updated the Eclipse download URL in the puppet manifest file:
`https://github.com/OSGP/Config/commit/b91d130bb24fba07c30de6b13706085ec6189ead`

There is no problem with cloning the open-smart-grid-platform repository using either git or https. I'm leaving the repository clone action as is.

The XSD files are not retrievable for the component osgp-adapter-ws-microgrids. An error occurs:
```
Microgrids

https://localhost/osgp-adapter-ws-microgrids/wsdl/MicrogridsAdHocManagement.wsdl

https://localhost/osgp-adapter-ws-microgrids/wsdl/schemas/adhocmanagement.xsd
XML Parsing Error: no root element found
Location: https://localhost/osgp-adapter-ws-microgrids/wsdl/schemas/adhocmanagement.xsd
Line Number 1, Column 1:

https://localhost/osgp-adapter-ws-microgrids/wsdl/schemas/common.xsd
XML Parsing Error: no root element found
Location: https://localhost/osgp-adapter-ws-microgrids/wsdl/schemas/common.xsd
Line Number 1, Column 1:
``` 
We'll look into these errors.

**Comment by ThE-MaRaC** [comment]
@kevinsmeets The problem with the git clone seems to have been only temporary, so please ignore it

**Comment by ThE-MaRaC** [comment]
Noticed one more issue in the latest code.
After the merge of [FLEX-5084: Filters events on description](https://github.com/OSGP/open-smart-grid-platform/pull/326) lombok plugin must be installed in order to compile the project in eclipse.

**Comment by kevinsmeets** [comment]
We are in the process of updating the documentation. Those changes will be avaiable soon.

**Comment by ThE-MaRaC** [comment]
Problem with the retrieval of osgp-ws-microgrids XSD files is still present. HTTP 405 is returned
```
::1 - - [19/Jun/2020:09:38:16 +0200] "GET /osgp-adapter-ws-microgrids/wsdl/microgrids/adHocManagementService/MicrogridsAdHocManagement.wsdl HTTP/1.1" 200 7252
::1 - - [19/Jun/2020:09:38:26 +0200] "GET /osgp-adapter-ws-microgrids/wsdl/microgrids/adHocManagementService/schemas/adhocmanagement.xsd HTTP/1.1" 405 -
::1 - - [19/Jun/2020:09:38:30 +0200] "GET /osgp-adapter-ws-microgrids/wsdl/microgrids/adHocManagementService/schemas/common.xsd HTTP/1.1" 405 -
```
Any additional config required or am I missing something?

**Comment by bvdzwet** [comment]
@ThE-MaRaC: thanks for reminding us. Regarding the 405 responses retrieving the Microgrids XSDs, I have created https://smartsocietyservices.atlassian.net/browse/OC-607
