### ISSUE TITLE
PublicLightingAdHocManagement.FindAllDevices response is incomplete

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#226]
Mapping between Device DB entity and Device object that is defined in pl-adhocmanagement.xsd is not correctly implemented, so FindAllDevices response does not contain all device information that is available in the DB.
- Device DB entity: org.opensmartgridplatform.core.db.api.entities.Device
- pl-adhocmanagement.xsd Device: org.opensmartgridplatform.adapter.ws.schema.publiclighting.adhocmanagement.Device

web-demo-app is using that operation and that same operation is mentioned in the [documentation](https://documentation.opensmartgridplatform.org/Userguide/Installation/testOSGP.html).
This is really misleading, any plans to update this operation or even remove it in favor of FindDevices operation from DeviceManagement, which is working correctly?

**Comment by smvdheijden** [comment]
@ThE-MaRaC, thank you for your feedback, we have created https://smartsocietyservices.atlassian.net/browse/OC-608 for fixing this issue.

**Comment by smvdheijden** [comment]
https://smartsocietyservices.atlassian.net/browse/OC-608 is done. 
@ThE-MaRaC could you confirm that we can close this issue now?

**Comment by ThE-MaRaC** [comment]
Looks OK.

New FindAllDevicesResponse
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <ns3:FindAllDevicesResponse xmlns:ns2="http://www.opensmartgridplatform.org/schemas/common/2014/10" xmlns:ns3="http://www.opensmartgridplatform.org/schemas/publiclighting/adhocmanagement/2014/10">
         <ns3:DevicePage>
            <ns3:TotalPages>1</ns3:TotalPages>
            <ns3:Devices>
               <ns3:DeviceUid>U1NMRF9PU0lKRUtfMDE=</ns3:DeviceUid>
               <ns3:DeviceIdentification>SSLD_OSIJEK_01</ns3:DeviceIdentification>
               <ns3:ContainerPostalCode>31000</ns3:ContainerPostalCode>
               <ns3:ContainerCity>Osijek</ns3:ContainerCity>
               <ns3:ContainerStreet>Reisnerova</ns3:ContainerStreet>
               <ns3:ContainerNumber>109</ns3:ContainerNumber>
               <ns3:GpsLatitude>45.554638</ns3:GpsLatitude>
               <ns3:GpsLongitude>18.674614</ns3:GpsLongitude>
               <ns3:Activated>false</ns3:Activated>
               <ns3:HasSchedule>false</ns3:HasSchedule>
               <ns3:PublicKeyPresent>false</ns3:PublicKeyPresent>
            </ns3:Devices>
         </ns3:DevicePage>
      </ns3:FindAllDevicesResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
