### ISSUE TITLE
Question : Problem with OSGP Platform set up

### ISSUE THREAD

**Issue by ramams** [OSGP/Documentation#230]
**Question:**
Stuck while setting up OSGP Platform. Need help.

**background:**
Hi,

I am new to OSGP. I have done the installation with vagrant and virtual box. There were no errors in "vagrant up". While setting up the platform as per https://documentation.opensmartgridplatform.org/Userguide/Installation/setupOSGP.html, I am getting 2 errors listed below with SmartMeteringMonitoring.wsdl file in Eclipse. Looks like the build is incomplete due to this. When I right click on the Tomcat server and select 'Add and Remove',  I get an error message: "There are no resources that can be added or removed from the server". BTW, I am also getting 468 warnings and 1 info. Not sure if this is normal. Please help me in getting OSGP up and running.

The part 'GetPowerQualityProfileRequest' has an invalid value 'GetPowerQualityProfileRequest' defined for its element. Element declarations must refer to valid values defined in a schema.	SmartMeteringMonitoring.wsdl	/osgp-ws-smartmetering/src/main/resources	line 157	WSDL Problem

The part 'GetPowerQualityProfileResponse' has an invalid value 'GetPowerQualityProfileResponse' defined for its element. Element declarations must refer to valid values defined in a schema.	SmartMeteringMonitoring.wsdl	/osgp-ws-smartmetering/src/main/resources	line 163	WSDL Problem

Thanks,
Rama
**

**Comment by ramams** [comment]
Update: Looks like the 2 WSDL errors are not related to Tomcat server "Add and Remove" issue I reported earlier. I pulled release-5.1.0 branch (thinking it would be more stable than developer branch) and followed the same steps of setting up the platform as per https://documentation.opensmartgridplatform.org/Userguide/Installation/setupOSGP.html. I still get those 2 WSDL errors. But, I am able to add resources, except for 3 resources related to protocol simulators (iec60870, iec61850 and mqtt). So, it looks like the issue has been introduced in developer branch. Is it ok if I continue with 5.1.0 branch? I am yet to complete remaining steps of platform setup as per the document mentioned above.

Thanks,
Rama

**Comment by kevinsmeets** [comment]
Hello @ramams,

Thank you for reporting this issue. I created a new development environment using Vagrant/VirtualBox. I see the errors you mentioned. Deploying the components to Tomcat 9 works fine. As you describe in your second comment, there is no relation between deploying to Tomcat and those WSDL/XSD errors.

If you prefer using the release branch, you certainly can use that version of the code. You should be able to complete the setup steps as described in the documentation.

I will have a look at the errors in WSDL/XSD.

**Comment by ramams** [comment]
Hi @kevinsmeets,

Thank you for your quick response. I was able to setup release branch and run the demo app successfully. I will continue to use the release branch for now. I will keep this issue open, so that I will know when the WSDL errors get resolved. We are interested in smart meter domain.

Regards,
Rama
