### ISSUE TITLE
Configuration required to test osgp-protocol-simulator-61850

### ISSUE THREAD

**Issue by sanjaydhonde** [OSGP/Documentation#239]
As per the documentation, **osgp-protocol-simulator-61850** requires additional confiiguration. 

We found that the simulator gets started successfully but there is **no communication** happening between simulator & protocol adapter.

**Could you please help and share the required configuration.**

**Comment by kevinsmeets** [comment]
Hello @sanjaydhonde,

for now, I'm going to point your attention to this issue: https://github.com/OSGP/Documentation/issues/238 
I think both issues/questions are getting at the same thing.

Which of the IEC61850 device types are interested in?

**Comment by sanjaydhonde** [comment]
Thanks Kevin.
