### ISSUE TITLE
MQTT Simulator & Broker component

### ISSUE THREAD

**Issue by sanjaydhonde** [OSGP/Documentation#241]
We have observed that MQTT broker and client which sends actual meter data to OSGP platform are embedded in a single project i.e. MQTT Simulator. Does that mean adding a new device would require its own Broker component to be added ? But as per our understanding, only MQTT client application would be there on actual devices and not MQTT Broker.  Is there any particular need to have Broker component in simulator?

Alternatively, can we create single MQTT broker and let all devices connect & push data to it. In that case, can existing MQTT Adapter still connect to this broker and automatically fetch the data. If yes, does this configuration need any changes in communication monitoring task?

**Comment by kevinsmeets** [comment]
We have chosen to let the platform (the protocol adapter component as an MQTT client) connect to a smart device / simulator, which means that the device is running a broker.

One could choose a different setup, where smart devices are running an MQTT client, these devices connect to some broker, and the devices publish data to a topic. The protocol adapter component as an MQTT client could also connect to that broker and subscribe to the given topic and receive the data published by the devices.

I guess the communication monitoring task could still be used to connect to the broker. How to configure the task would depend on the behavior of the smart devices, and how the device records are set up within the platform.
