### ISSUE TITLE
SSLD/LMD GetStatusResponse is not according to the XSD schema

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#242]
When SSLD relay is switched off, GetStatusResponse will have DimValue set to 0, but according to XSD schema only values from 1 to 100 are allowed.
pl-adhocmanagement.xsd
```
<xsd:element minOccurs="0" name="DimValue">
  <xsd:simpleType>
    <xsd:restriction base="xsd:int">
      <xsd:minInclusive value="1" />
      <xsd:maxInclusive value="100" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:element>
```
osgp-adapter-ws-public-lighting.log
```
2020-12-21 16:05:30.846] [3c1f26f7506a] [ajp-nio-0.0.0.0-8009-exec-9] INFO o.o.a.w.e.WebServiceMonitorInterceptor@printSoapMessage:338 - soap message: <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<ns2:GetStatusResponse xmlns:ns2="http://www.opensmartgridplatform.org/schemas/publiclighting/adhocmanagement/2014/10" xmlns:ns3="http://www.opensmartgridplatform.org/schemas/common/2014/10">
			<ns2:Result>OK</ns2:Result>
			<ns2:DeviceStatus>
				<ns2:LightValues>
					<ns2:Index>2</ns2:Index>
					<ns2:On>false</ns2:On>
					<ns2:DimValue>0</ns2:DimValue>
				</ns2:LightValues>
				<ns2:LightValues>
					<ns2:Index>3</ns2:Index>
					<ns2:On>false</ns2:On>
					<ns2:DimValue>0</ns2:DimValue>
				</ns2:LightValues>
			</ns2:DeviceStatus>
		</ns2:GetStatusResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by kevinsmeets** [comment]
Thank you for reporting this issue, @ThE-MaRaC. I created an initial change which resolves this items. I did find that a client application is now showing `null` instead of `0` for the dim value when the relay state is `off`. Therefore I will have to make a little change to this client application as well.

**Comment by ThE-MaRaC** [comment]
Sorry for the late response, I was on vacation.
Please let me know if you need any kind of assistance.

**Comment by ThE-MaRaC** [comment]
A similar error occurs when we try to get status from the LMD.
```
<ns2:LightValues>
    <ns2:Index>1</ns2:Index>
    <ns2:On>false</ns2:On>
    <ns2:DimValue>-1</ns2:DimValue>
</ns2:LightValues>
```
As you can see DimValue is -1.
So, can you please check if this case is also fixed?

**Comment by ThE-MaRaC** [comment]
Is there any specific reason why this correction is still not merged? Do you need anything else from my side?

**Comment by kevinsmeets** [comment]
https://github.com/OSGP/open-smart-grid-platform/pull/885
