### ISSUE TITLE
DLMS device simulator

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#246]
We would like to test SmartMetering part of OSGP, but DLMS simulator is not part of this repository.

Is there any other place where it can be downloaded?

According to the [OC-682](https://smartsocietyservices.atlassian.net/browse/OC-682) it is planned to move simulator source code to this repository.

**Comment by rtusveld** [comment]
It is correct that it is planned to move simulator source code to OSGP. These activities are planned for Q3. We understand your need and will try to move the code in the coming period.

**Comment by kevinsmeets** [comment]
Closing this issue as it has been mentioned several times in the past and will be performed some time in the future ;)

**Comment by bvdzwet** [comment]
The DLMS simulator has been placed in the open-smart-grid-platform repository, see: OSGP/open-smart-grid-platform#727.
Some info regarding high level concepts about how this simulator works and is integrated with the Cucumber tests can be found in the following additions to the documentation: OSGP/Documentation#270.
