### ISSUE TITLE
SOAPUI and SmartMetering WSDL

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#256]
While trying to setup SoapUI we noticed that it is not possible to retrieve common-ws-smartmetering.xsd file, an HTTP 405 error occurs.
Bean name in osgp/shared/osgp-ws-smartmetering/src/main/java/org/opensmartgridplatform/ws/smartmetering/config/SmartmeteringWebServiceConfig.java, line 63 is wrong and should be renamed to match XSD name:
`@Bean(name = "commo-ws-smartmeteringn") -> @Bean(name = "common-ws-smartmetering")`

**Comment by bvdzwet** [comment]
Thanks for reporting this. It looks like you caught something that slipped through the review process for some changes last week.

Pull request open-smart-grid-platform#662 that should fix the issue you reported was just merged.

**Comment by ThE-MaRaC** [comment]
Problem is fixed.
