### ISSUE TITLE
Smart Metering DeviceIdentification length

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#257]
DeviceIdentification in Smart Metering domain is defined as follows:
```
<xsd:simpleType name="DeviceIdentification">
  <xsd:restriction base="tns:AlphaNumericType">
    <xsd:length value="17"/>
  </xsd:restriction>
</xsd:simpleType>
```

But, according to the DLMS COSEM specification DeviceIdentification length should be 16.
Here is the relevant part of the specification (DLMS UA 1000-1:2010, Ed. 10.0, 2010-08-26)
> The logical device name is defined as an octet-string of up to 16 octets. The first three octets shall carry the manufacturer identifier. The manufacturer shall ensure that the logical device name, starting with the three octets identifying the manufacturer and followed by up to 13 octets, is unique.

**Comment by bvdzwet** [comment]
As far as I have come to understand, the logical device name refers to a logical device, of which several can exist in a single physical DLMS device according to the specifications.

The DeviceIdentification refers to the E-meter equipment identifier as used by manufacturers to identify the physical devices.

**Comment by ThE-MaRaC** [comment]
Can you please provide OBIS code that holds E-meter equipment identifier?
I have Iskraemeco ME382-D1 smart meter and I am not able to find such ID which is 17 chars long.
In the attachment you can find the manual which describes my meter, Chapter 7 explains Identification numbers.
[ME382-INSTALLATION-MANUAL.pdf](https://github.com/OSGP/Documentation/files/6790893/ME382-INSTALLATION-MANUAL.pdf)

**Comment by bvdzwet** [comment]
The OBIS code that holds the device ID for the identifier used as DeviceIdentification would be 0-0:96.1.1.255.
That would be Device ID 2 from DLMS, which you could find in the Blue Book with the "OBIS codes for abstract objects, general service entries".
This is defined as a 17 character E-meter equipment identifier in the Dutch DLMS companion standard DSMR.

**Comment by ThE-MaRaC** [comment]
This is exactly the same OBIS code that I have checked and on ME382 it's empty.
Check the attached screenshot.
![ME382](https://user-images.githubusercontent.com/3833748/125084938-58a29e00-e0ca-11eb-97f7-9614d8338053.png)

**Comment by stefanermens** [comment]
Our apologies for the late response. We close this issue for now. If you still need any help on this issue, please let us know.
