### ISSUE TITLE
Broken Links: No PDF | Development branch publication in PDF

### ISSUE THREAD

**Issue by GrooveCS** [OSGP/Documentation#261]
The URL is broken both in Master & Development [README.md](https://github.com/OSGP/Documentation/tree/development) Branches and in [GitBook](documentation.gxf.lfenergy.org/).

![Broken Links](https://user-images.githubusercontent.com/1635152/127515749-d91aeaa0-0e24-49d2-ad89-6a308583edc3.png)

**Comment by rtusveld** [comment]
We changed some of the references to fix the problems stated above. All these issues should be fixed.
