### ISSUE TITLE
Problem with SOAP UI and SmartMetering IF

### ISSUE THREAD

**Issue by ThE-MaRaC** [OSGP/Documentation#262]
While trying to setup SoapUI we noticed that it is not possible to retrieve osgp-ws-smartmetering XSD files, an HTTP 405 error occurs.
```
curl -s -o /dev/null -w '%{http_code}' https://localhost/osgp-adapter-ws-smartmetering/wsdl/smartMetering/installationService/schemas/base-ws-smartmetering.xsd
405
```
Similar problem was reported in https://github.com/OSGP/Documentation/issues/221

**Comment by stefanermens** [comment]
Our apologies for the late response. We have put this issue on our backlog. We will try to solve this in the similar way as #221.
