### ISSUE TITLE
Problems creating Virtual Machine

### ISSUE THREAD

**Issue by esantosf** [OSGP/Documentation#275]
[logVM.docx](https://github.com/OSGP/Documentation/files/8117376/logVM.docx)

**Comment by kevinsmeets** [comment]
Hello @esantosf ,

a couple of changes have been made to the Vagrant file and the puppet scripts.
You should be able to create a Virtual Machine which contains git, java-11-sdk, eclipse, activemq, postgresql, httpd, etc. using this new version.

I did find at least 2 problems:
- PgAdmin doesn't work very well; you can use psql instead
- the web-demo-app is missing a dependency that causes the SOAP client to malfunction; you can use SoapUI instead

Kind regards, Kevin
