### ISSUE TITLE
HTTP 500 when attempting to add device to web demo app

### ISSUE THREAD

**Issue by NinjaJc01** [OSGP/Documentation#276]
After installing the development VM in VirtualBox with Vagrant and following the steps outlined in the documentation, attempting to add a device or list devices in the web-demo-app results in a null pointer exception and 500 error.
The stack trace for adding a device is attached:
[OSGP-Stack-Trace.txt](https://github.com/OSGP/Documentation/files/8421367/OSGP-Stack-Trace.txt)

**Comment by JelleHoffman** [comment]
Hello @NinjaJc01, first of all thanks for reporting this issue and using our software!

There are some package problems within the vagrant image. Therefore the Soap calls don't work as they should at the moment. We have put an item on our backlog to fix this. For now you can use SoapUI to add devices. Also see #275 for more information.
