### ISSUE TITLE
OSLP implementation, decrypt web simulator messages

### ISSUE THREAD

**Issue by scordedda** [OSGP/Documentation#277]
Hi,

I am working with the OSLP protocol, I am able to use the entire test environment present in the VM. I can create a device using the web simulator, register it and change its state using SoapUI.

Now I want the web simulator to communicate with a my java application, I created a java socket server that listens to port 12122, after modifying the "web-device-simulator.properties" file to point to the IP address of my machine, when the server socket is running I can receive messages from the web simulator.

For example, if I execute the command "Register device" I receive a message similar to the following on the web server

`3045022100EC38384AA6ABA489E2FEE8CC550CADCB4709A8BD3A796A82F1933FCD513E3E1402201031CDA8328583F59A1D8215D0C86184C6431AC5291DC98659AB2698B7C09A4500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000093DD0001C6C4E18EA7B81151546000200A1E0A0E53534C445F3030302D30302D303112047F0000011801200028B7C6020`

Hex to String

`0E!�ì88J¦«¤‰âþèÌU­ËG	¨½:yj‚ñ“?ÍQ>> 1Í¨2…ƒõš‚ÐÈa„ÆCÅ)É†Y«&˜·ÀšE���������������������������������������������������������“Ý�ÆÄáŽ§¸QT`� 

**SSLD_000-00-01**�� �(·Æ` 

(**Device ID in bold font**)

It looks like an encrypted message with only the clear device ID.

How should I handle this message to send the response to the web simulator?

Thank you

**Comment by kevinsmeets** [comment]
Hello @scordedda ,

There is some documentation here: [https://documentation.gxf.lfenergy.org/protocols/oslp/index.html](https://documentation.gxf.lfenergy.org/protocols/oslp/index.html).

The message you are receiving contains a security key (which is an encrypted hash), a sequence number, a unique device identification, the length of the payload, and a payload (which indicates the message type and contains values).

The message in total is not encrypted, only the security key is, which is used to sign and validate the message content.

To read the message, stick to the length of the components that make up the message as described in the documentation link above.

The security key should be decrypted using the platform public key, and the resulting hash should be compared to the message, see implementation [here](https://github.com/OSGP/open-smart-grid-platform/blob/60e7337a7e37fa8c99c7af004991c20ee212d6a9/osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp/OslpEnvelope.java#L197).

The sequence number is a 16-bit unsigned integer and has to be included in the response to the request message. It can be read using a bit mask and byte shifting, see implementation [here](https://github.com/OSGP/open-smart-grid-platform/blob/development/osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/SequenceNumberUtils.java).

The unique device identification is a base 64 encoded string (something like this for example 'dGVzdDEyMzQ1Njc4') and is not the same as the simple device identification like 'SSLD_000-00-01'.

The length of the payload is a 16-bit unsigned integer.

The payload of the message is encoded using Google Protobuf.
There's a generated java class that can parse the payload: [Oslp.java](https://github.com/OSGP/open-smart-grid-platform/blob/60e7337a7e37fa8c99c7af004991c20ee212d6a9/osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp/Oslp.java).
This class is generated from the [Protobuf Contract](https://documentation.gxf.lfenergy.org/protocols/oslp/oslp-v0.6.1/oslp.proto.v0.6.1.html).

For the register device request, in particular, see this documentation: [https://documentation.gxf.lfenergy.org/protocols/oslp/oslp-v0.6.1/registerdevice.html](https://documentation.gxf.lfenergy.org/protocols/oslp/oslp-v0.6.1/registerdevice.html)
It shows an example of the request message payload and the response message payload and describes the values of these payloads.

Creating a response will need a number of the components of the request message and a response payload.
- security key, which is the encrypted hash of the components of the response message, encrypted with 'SHA256withECDSA' using the device private key
- sequence number, as obtained from the request and property masked and shifted
- unique device identification encoded as base 64, as obtained from the request
- length of the payload, property masked and shifted
- the register device response payload encoded using Google Protobuf

The bytes of the response message need to be written to the same TCP connection as initiated by the device simulator when the request message was sent.

**Comment by scordedda** [comment]
Hi @kevinsmeets 

Thank you for your answare, I have continue the implementataion using your suggestion, now I’m able to read the data sent from the web device simulator opening a web socket with the Netty framework, using the class present here [open-smart-grid-platform/osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp at development · OSGP/open-smart-grid-platform (github.com)](https://github.com/OSGP/open-smart-grid-platform/tree/development/osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp).

Actually I’m having some problems:

 1) I’m no able to decode the security key, I have tried using the public key presents here [Config/certificates/oslp at development · OSGP/Config (github.com)](https://github.com/OSGP/Config/tree/development/certificates/oslp) but it  seems not to be correct.


 2) About the generation of the response, for the point “security key, which is the encrypted hash of the components of the response message, encrypted with 'SHA256withECDSA' using the device private key”, which is the private key that I have to use?


3) Is necessary a specific version of the protobuf to validate the message received from the web simulator?

4) I saw that in the virtual machine containing the implementation of the whole protocol are presents two similar implementations (“[web-device-simulator](https://github.com/OSGP/open-smart-grid-platform/tree/development/osgp/protocol-adapter-oslp/web-device-simulator)” and “[osgp-adapter-protocol-oslp-elster](https://github.com/OSGP/open-smart-grid-platform/tree/development/osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster)”), but they differ in some implementations steps and in the data structures, for example, which we should use between 
OslpChannelHandler  (web simulator) and OslpChannelHandlerServer  (Elster)?


5) What implementation do we refer to to create the socket server? Elster (public class OslpChannelHandlerServer extends OslpChannelHandler) or the web simulator (public class OslpChannelHandler extends SimpleChannelInboundHandler <OslpEnvelope>)?


Thank you

**Comment by kevinsmeets** [comment]
Hello @scordedda ,

1. You need this public key: [oslp_sim_ecdsa_public](https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_sim_ecdsa_public.pem) as the simulator uses this private key when creating a request: [oslp_sim_ecdsa_private](https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_sim_ecdsa_private.pem)

Maybe these unit tests can show you how to process the bytes: [OslpEnvelopeEcDsaTest](https://github.com/OSGP/open-smart-grid-platform/blob/86ed334b749211f03ae65d4f9695cd6c67635805/osgp/protocol-adapter-oslp/oslp/src/test/java/org/opensmartgridplatform/oslp/OslpEnvelopeEcDsaTest.java#L64). This test code shows the classes and functions used.

2. You need this private key when creating a response: [oslp_test_ecdsa_private](https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_test_ecdsa_private.pem) as the simulator uses this public key to validate the response: [oslp_test_ecdsa_public](https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_test_ecdsa_public.pem)

This is configured for the simulator here: [web-device-simulator.properties](https://github.com/OSGP/open-smart-grid-platform/blob/86ed334b749211f03ae65d4f9695cd6c67635805/osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/web-device-simulator.properties#L41)

3. The version of `protobuf-java` is [2.4.1](https://github.com/OSGP/open-smart-grid-platform/blob/86ed334b749211f03ae65d4f9695cd6c67635805/super/pom.xml#L122). That is an old version and I don't know if this version would be compatible with higher versions. This version is required for us, as we use hardware that has been developed based on this version.

4. The simulator is simplistic and implements the minimal required to be useful for some basic manual tests. The protocol adapter component is the complete implementation. I would use the protocol adapter classes.

5. Same consideration as 4. I would use the protocol adapter classes.

**Comment by scordedda** [comment]
Hi @kevinsmeets ,

I'm trying to send the response to the web simulator using the key that you have suggested, but I'm haveing some errors:

This is the my code used for test


```
@Override
	protected void channelRead0(ChannelHandlerContext ctx, OslpEnvelope message) throws Exception {
        final ChannelId channelId = ctx.channel().id();

        **logRegisterReq(message);**

        if (message.isValid()) {
            if (OslpUtils.isOslpResponse(message)) {
                LOGGER.warn("{} Received OSLP Response, which is not expected: {}", channelId,
                        message.getPayloadMessage());
                ctx.close();
            } else {
                
                
                LOGGER.info("{} Received OSLP Request: {}", channelId, message.getPayloadMessage());

                // Response pay-load to send to device.
                final Message payload;

                // Check which request the device has sent and handle it.
                if (message.getPayloadMessage().hasRegisterDeviceRequest()) {
                    payload = this.handleRegisterDeviceRequest(message.getDeviceId(), message.getSequenceNumber(),
                            message.getPayloadMessage().getRegisterDeviceRequest());
                                    
                    System.out.println("RESPONSE: " + payload.toString());

                } else {
                    LOGGER.warn("{} Received unknown payload. Received: {}.", channelId, message.getPayloadMessage());
                    ctx.close();
                    // Optional extra: return error code to device.
                    return;
                }

            
                final OslpEnvelope respBuilder = new OslpEnvelope.Builder()
                        .withSignature(OslpServer.SIGNATURE)
                        .withProvider(OslpServer.PROVIDER_ORACLE)
                        .withPrimaryKey(CertificateHelper.createPrivateKeyFromBase64(
                        		OslpServer.PRIVATE_KEY_BASE_64, OslpServer.KEY_TYPE, OslpServer.PROVIDER_ORACLE))
                        .withDeviceId(message.getDeviceId())
                        .withSequenceNumber( message.getSequenceNumber())
                        .withSecurityKey(message.getSecurityKey())
                        .withPayloadMessage(payload).build();
               
                ctx.channel().writeAndFlush(respBuilder);

            }
        }
	}
```

The method  **logRegisterReq(message);**_is used to print the received data from the register device request

This is the code

	

```
	    private void **logRegisterReq(OslpEnvelope msg)** {
		Message x = msg.getPayloadMessage();

		System.out.println("--- Payload ----\n" +
				"Seq n   ->  " + SequenceNumberUtils.convertByteArrayToInteger(msg.getSequenceNumber()));
		System.out.println("Dev Id  ->  " + Base64.encodeBase64String(msg.getDeviceId()));
		System.out.println("Sec Key ->  " + msg.getSecurityKey() + "\n--- Payload ----");
		System.out.println("dev id  ->  " + x.getRegisterDeviceRequest().getDeviceIdentification());
		System.out.println("dev typ ->  " + x.getRegisterDeviceRequest().getDeviceType());
		System.out.println("ip add  ->  " + x.getRegisterDeviceRequest().getIpAddress());
		System.out.println("has sch ->  " + x.getRegisterDeviceRequest().hasHasSchedule());
		System.out.println("rand d  ->  " + x.getRegisterDeviceRequest().getRandomDevice());

		System.out.println("Is valid?  " + msg.isValid());
		
		System.out.println("END\n");
	    System.out.println("REQUEST: "+ x);
    }
``` 
    
  and this is the printed output
    
    

> --- Payload ----
Seq n   ->  35604
Dev Id  ->  AAHGxOGOp7gRUVRg
Sec Key ->  [B@182d5ae3
--- Payload ----
dev id  ->  SSLD_000-00-01
dev typ ->  SSLD
ip add  ->  com.google.protobuf.ByteString@721926
has sch ->  true
rand d  ->  13005
Is valid?  true
END

> REQUEST: registerDeviceRequest {
> 
>   deviceIdentification: "SSLD_000-00-01"
>   ipAddress: "\000\000\001"
>   deviceType: SSLD
>   hasSchedule: false
>   randomDevice: 13005
> }



The following is the response that I'm generating

> RESPONSE: registerDeviceResponse {
  status: OK
  currentTime: "20220728120748"
  randomDevice: 13005
  randomPlatform: 58306
  locationInfo {
    latitude: 50889228
    longitude: 5974140
  }
}

the value _randomPlatform_, an the object _locationInfo_ are populated randomly

The value used to generate the _OslpEnvelope respBuilder_ builder are:


```
SIGNATURE = "SHA256withECDSA";
PROVIDER_ORACLE = "SunEC";
PRIVATE_KEY_OSLP = "MHcCAQEEIBcXK1z7Y1w9mkQwqVPmRRAd1CFKVnRL3oymNyz6J0HKoAoGCCqGSM49AwEHoUQDQgAEow7CWR7EiNDRt1XQ/h1UrLE24zY3BkA582mfiywZ2h8tPkwleCBfcyLeZvS0T4NGz+zzO5CZphlD1TQtjL/ZXg=="; (https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_test_ecdsa_private.pem)
KEY_TYPE = "EC";


```
In this way using the key: **PRIVATE_KEY_OSLP**
I'm receiving this erron in my application _Unexpected exception from downstream: org.opensmartgridplatform.shared.exceptionhandling.EncrypterException: Security exception creating private key for algorithm "EC" by provider "SunEC"_

Instead using this key get from the web simulato unit test
```
PRIVATE_KEY_BASE_64 = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg8ydsIOMoTlBPn6rJezELYFLUUuQe"
            + "3GvrhI3TDJj1yNyhRANCAAQ0UmJgxWImQ5wgepQ65nlsK0lvYb/GW6nx4ngLgncDZmWH3Pck8eC1"
            + "xsKg1goWpvl7P1um4cIjKyBwfqf8FxZa";
```

the my application generate correctly the response published above, but the web simulatore respond with this error:

```
2022-07-28 10:24:18.707] [dev-box] [ajp-nio-8009-exec-11] INFO o.o.w.service.OslpChannelHandler@send:434 - Connection established to: /10.0.131.155:12122
2022-07-28 10:24:19.084] [dev-box] [disposableNioEventLoopGroup-2-4] INFO o.o.w.service.OslpChannelHandler@isRebooting:633 - Checking whether device AAHGxOGOp7gRUVRg is rebooting
2022-07-28 10:24:19.084] [dev-box] [disposableNioEventLoopGroup-2-4] INFO o.o.w.service.OslpChannelHandler@channelRead0:312 - Process envelope for device AAHGxOGOp7gRUVRg, not rebooting
2022-07-28 10:24:19.088] [dev-box] [disposableNioEventLoopGroup-2-4] WARN o.o.w.service.OslpChannelHandler@channelRead0:388 - Received message wasn't properly secured.
```



Could you help me? Do you have some suggestion?

Thank you

**Comment by kevinsmeets** [comment]
Hello @scordedda ,

your second attempt is using the wrong private key, but the key is properly encoded which is the reason the creation of a response message is successful, followed by an error `Received message wasn't properly secured.` as seen in the simulator logging.

Your first attempt was OK, but not using the proper encoding.
You can try to use the following encoded [private key](https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_test_ecdsa_private.der) using [https://www.motobit.com/util/base64-decoder-encoder.asp?charset=utf-8&acharset=](https://www.motobit.com/util/base64-decoder-encoder.asp):

`String PRIVATE_KEY_BASE_64 =
      "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgFxcrXPtjXD2aRDCpU+ZFEB3UIUpW\n"
          + "dEvejKY3LPonQcqhRANCAASjDsJZHsSI0NG3VdD+HVSssTbjNjcGQDnzaZ+LLBnaHy0+TCV4IF9z\n"
          + "It5m9LRPg0bP7PM7kJmmGUPVNC2Mv9le";`


So this is the same private key as mentioned before, the only difference is the encoding.

Alternatively, you could use [private key](https://github.com/OSGP/Config/blob/development/certificates/oslp/oslp_test_ecdsa_private.der) file and read it using this [function](https://github.com/OSGP/open-smart-grid-platform/blob/86ed334b749211f03ae65d4f9695cd6c67635805/osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/security/CertificateHelper.java#L40) from the file system.

**Comment by scordedda** [comment]
Hi kevinsmeets, 

thank you for your help, now we are able to get the device request and send the response.

As for second step we are trying to send a request to the device, in our specific case the 

"_SetLightRequest (from platform to device) is a request that notifies the device to switch on or off one ore several light relays, optionally with a dim-value per relay._" (OSLP v.0.6.1)

Refering to the method "_setLight_" from the _OslpDeviceService_  class (package _org.opensmartgridplatform.adapter.protocol.oslp.elster.infra.networking_) in _ELSTER_ project, we have tried to execute the request as follow with no success.


        List<LightValueDto> list = new ArrayList<LightValueDto>();

        DeviceRequest.Builder setLightDeviceRequestBuilder = DeviceRequest.newBuilder()
                .deviceIdentification("SSLD_test2");

        boolean lightON = true;
        LightValueDto dtoLight = new LightValueDto(0, lightON, 100);

        list.add(0, dtoLight);

        LightValueMessageDataContainerDto lightValueMessageDataContainer = new LightValueMessageDataContainerDto(list);

        final SetLightDeviceRequest deviceRequest = new SetLightDeviceRequest(setLightDeviceRequestBuilder,
                lightValueMessageDataContainer);


We have some doubts:

- Are we creating the request correctly? If not, could you give us an example?
- How we can send a request to the device simulator using the previous request? We are trying to send the request from a server application with Netty that is connected using the port 12122
- Is it the previous point correct or we have to use a REST service to do the request?
- Do you have an example of a correct implementation of the "SetLigth" request made from an external application from OSGP?

Thank you

```

**Comment by kevinsmeets** [comment]
Hello @scordedda ,

You are creating the correct object I think, so that is fine. The object will have to be converted to an OslpEnvelope object.
To send the request a TCP client will have to create a connection to the device simulator; you mention you have a server application with a connection from the device simulator, but you can not send a request to the simulator using that connection.
Netty can be used as a server and client, which is what we have used.
See the implementation we are using [here](https://github.com/OSGP/open-smart-grid-platform/blob/d2cd7f199d5d4336e7b75d947c4dcac00fb1b975/osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/OslpDeviceService.java#L2461).

Here is an implementation of the function in the simple demo [application](https://github.com/OSGP/open-smart-grid-platform/blob/d2cd7f199d5d4336e7b75d947c4dcac00fb1b975/public-lighting-demo-app/web-demo-app/src/main/java/org/opensmartgridplatform/webdemoapp/web/controller/PublicLightingController.java#L96). It sends a SOAP message to the OSGP web-service.

**Comment by scordedda** [comment]
Thank you  for you answer kevinsmeets,

now we are able to create a netty client that open a connection with the web device simulator connection on the elster port 12124.
We are trying to send a request to the device to turn-on the light. In the examples that you sent us, it is used the _send()_ method, the received parameters need the ResumeScheduleDeviceRequest Object, but we are not able to generate it because we are working in a Java environment that is not based on Spring framework. Without Spring we don't have the "Dto object".

We tried to send the following "_OslpEnvelp object_" using the _writeAndFlush()_ method of ChannelFuture class 

```
ChannelFuture f = b.connect(HOST, PORT).sync();          
f.channel().writeAndFlush(createOslpEnvelope());
```

```
public OslpEnvelope createOslpEnvelope()
{
    try {
        // Build the OslpEnvelope 
        final OslpEnvelope.Builder respBuilder = new OslpEnvelope.Builder().withSignature(OslpServer.SIGNATURE)
                .withProvider(OslpServer.PROVIDER_ORACLE)
                .withPrimaryKey(CertificateHelper.createPrivateKeyFromBase64(OslpServer.PRIVATE_KEY_BASE_64,
                        OslpServer.KEY_TYPE, OslpServer.PROVIDER_ORACLE))
                .withDeviceId(deviceId.getBytes()).withSequenceNumber(seqNumb.getBytes());
        
        OslpEnvelope response = respBuilder.build();
        return response;
    } catch (Exception e) {
        e.printStackTrace();
        return null;
    }
}
```

There seems to be a weird interaction between "ManufacturerId /DeviceId" and the OslpEnvelope.Builder methods "withDeviceId/withSequenceNumber". In short we are providing a wrong combination of the twos, as the system throw us an illegal argument exception.
We have tried to provide the two methods with different combinations of parameters that you can see with the following cases:

1) Real device id and sequence number gets from the web device simulatore DevID: **SSLD_000-00-01** seq. num. : **11699** _error: SequenceNumber is not of expected Length: 2_

2) **SSLD_000-00-01** seq. num. : **11** (Wrong)  _error: "ManufacturerId + DeviceId is not of expected Length: 12"_ 

3) DevID: **111111111111** (length 12 - Wrong) seq.num **11** (Wrong), the OslpEnvelope object is created correctly and in the Web Device Simulator we see the messages:

```
2022-09-12 15:23:50.648] [dev-box] [disposableNioEventLoopGroup-4-6] INFO o.o.w.application.config.OslpConfig@initChannel:118 - Created server new pipeline
2022-09-12 15:23:50.649] [dev-box] [disposableNioEventLoopGroup-4-6] INFO o.o.w.service.OslpChannelHandler@channelActive:394 - Channel 890c6f3d active.
2022-09-12 15:23:50.729] [dev-box] [disposableNioEventLoopGroup-4-6] INFO o.o.w.service.OslpChannelHandler@isRebooting:633 - Checking whether device MTExMTExMTExMTEx is rebooting
2022-09-12 15:23:50.730] [dev-box] [disposableNioEventLoopGroup-4-6] INFO o.o.w.service.OslpChannelHandler@channelRead0:312 - Process envelope for device MTExMTExMTExMTEx, not rebooting
```

Could you help us to send the correct message to turn on/off the light status?

Thank you

**Comment by kevinsmeets** [comment]
Hello @scordedda ,

I see you are trying to use `.getBytes()` for the values of device identification and sequence number. This will not work.
These values will have to be properly encoded; base 64 for the device identification and byte shifted and masked for the sequence number.

Alternatively, you could consider using the byte values you received from the device registration messages. The device registration request should contain a 10-byte device UID which you could reuse and the same for the 2-byte sequence number.

Further, I think you should use the bytes [0,1] as manufacturer ID. These 2 bytes + the 10 bytes device UID will be 12 bytes which should be used to create a request (set light request in your case).

- I don't understand the remark about Spring Framework; you don't have to use Spring Framework if you don't want to, what do you mean by this remark?
- Regarding the resume schedule request; in our code base, we are indeed sending multiple requests in a particular order. I don't think you have to do this, it is a functional detail for the hardware devices we are using.
- The logging lines you include show something about a reboot of a device; I don't think this has something to do with your request.

**Comment by scordedda** [comment]
Hi @kevinsmeets , thank you for your support,

my need is to be able to send requests to devices, in this case the setLight (). I'm trying to send the setLight to the device using this builder 

```           
 final OslpEnvelope.Builder reqBuilder = new OslpEnvelope.Builder().withSignature(OslpServer.SIGNATURE)
        .withProvider(OslpServer.PROVIDER_ORACLE)
        .withPrimaryKey(CertificateHelper.createPrivateKeyFromBase64(OslpServer.PRIVATE_KEY_BASE_64,
                OslpServer.KEY_TYPE, OslpServer.PROVIDER_ORACLE))
                    .withDeviceId(deviceId.getBytes()).withSequenceNumber(seqNumb.getBytes()).withPayloadMessage(**payloadMessage**);

 OslpEnvelope request= reqBuilder.build();
```

and sending it with the 

```
ChannelFuture f = b.connect(HOST, PORT).sync();          
f.channel().writeAndFlush(request);
```

Is this correct?
If this is correct,
How I can create the ** payloadMessage ** to turn on the light?

Thank you

Sergio

**Comment by kevinsmeets** [comment]
The usage of the netty channel is OK, I think.

You can use the [Oslp java](https://github.com/OSGP/open-smart-grid-platform/blob/development/osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp/Oslp.java) implementation to create the payload.
Something like this:

```
Integer index = 0;
boolean isOn = true;
Integer dimValue = 100;

// use the Oslp classes and builders
final Oslp.SetLightRequest.Builder setLightRequestBuilder = Oslp.SetLightRequest.newBuilder();

// add light values to the Oslp.SetLightRequest.Builder
final Oslp.LightValue.Builder builder = Oslp.LightValue.newBuilder();
builder.setIndex(ByteString.copyFrom(new byte[] {index.byteValue()}));
builder.setOn(isOn);
builder.setDimValue(ByteString.copyFrom(new byte[] {dimValue.byteValue()}));

setLightRequestBuilder.addValues(builder.build());

// create the bytes for device identification and sequence number
final byte[] deviceId = Base64.decodeBase64(deviceUid);
final byte[] sequenceNumber = SequenceNumberUtils.convertIntegerToByteArray(sequenceNumber);

// create message with payload
Oslp.Message payloadMessage = Oslp.Message.newBuilder().setSetLightRequest(setLightRequestBuilder.build()).build();

final OslpEnvelope request =
    new OslpEnvelope.Builder()
            .withDeviceId(deviceId)
            .withSequenceNumber(sequenceNumber)
            .withPrimaryKey(privateKey)
            .withSignature(signature)
            .withProvider(signatureProvider)
            .withPayloadMessage(payloadMessage)
            .build();

// send the Oslp envelope using your netty TCP client
ChannelFuture f = b.connect(HOST, PORT).sync();          
f.channel().writeAndFlush(request);
```

See here: 
- https://github.com/OSGP/open-smart-grid-platform/blob/2fcefdb015fa0da48ff52abb7c9e8e1bd16c359b/osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/OslpDeviceService.java#L1621
- https://github.com/OSGP/open-smart-grid-platform/blob/2fcefdb015fa0da48ff52abb7c9e8e1bd16c359b/osgp/protocol-adapter-oslp/signing-server/src/main/java/org/opensmartgridplatform/signing/server/application/services/SigningService.java#L89

**Comment by scordedda** [comment]
Hi kevinsmeets, thanks for your previous answers.

Now we are able to send a request to the device, however, we still have problems with the "**setlitgh**" because we are unable to obtain the unique identification of the device.
From what you wrote above, the unique device identification is a base 64 encoded string and does not match the simple device identification such as '_SSLD_000-00-01_'.
As you suggested, we also tried to use bytes [0,1] as manufacturer ID but we can't get the 10 byte device UID starting from the string "_SSLD_000-00-01_".

Could you tell us how we can do starting from the string '_SSLD_000-00-01_' to build the deviceUid to pass to our builder?

Currently our code looks like this:


```
   String deviceIdString = "_SSLD_000-00-01_";

            // create the bytes for device identification and sequence number
            final byte [] deviceId = Base64.decodeBase64 (deviceIdString);
            final byte [] sequenceNumber = SequenceNumberUtils.convertIntegerToByteArray (seqNumb);

            byte [] deviceUid = ArrayUtils.addAll (new byte [] {0, 1}, deviceId);

            // Build the OslpEnvelope
            final OslpEnvelope.Builder respBuilder = new OslpEnvelope.Builder (). withSignature (signature)
                    .withProvider (provider)
                    .withPrimaryKey (primaryKey)
                    .withDeviceId (deviceUid)
                    .withSequenceNumber (sequenceNumber)
                    .withPayloadMessage (lightRequest ());


            ChannelFuture f = b.connect (HOST, PORT) .sync ();
            f.channel (). writeAndFlush (request);

```

to the writeAndFlush statement. 
In the simulator console we see this response:

INFO o.o.w.service.OslpChannelHandler@handleRequest: 494 - request received, sequenceNumber: 11700
INFO o.o.w.service.OslpChannelHandler@handleRequest: 495 - manufacturerId byte [0]: 0 byte [1]: 1
INFO o.o.w.service.OslpChannelHandler@handleRequest: 496 - deviceId as BASE 64 STRING: AAFJIsP / TTT7TT7T
WARN o.o.w.service.OslpChannelHandler@exceptionCaught: 409 - Unexpected exception from downstream.
org.opensmartgridplatform.webdevicesimulator.exceptions.DeviceSimulatorException: device with id: AAFJIsP/TTT7TT7T is unknown

The SSLD_000-00-01 device was created on the simulator and its deviceUid generated during creation should be AAHGxOGOp7gRUVRg (and not AAFJIsP/TTT7TT7T).
How can we get to the deviceUid "AAHGxOGOp7gRUVRg" starting from the string "SSLD_000-00-01" to turn on the light bulb of the device "SSLD_000-00-01"?

Thank you

**Comment by kevinsmeets** [comment]
Hello @scordedda ,

you can not derive the (unique generated) deviceUID from the (human readable) device identification like  "SSLD_000-00-01". The device simulator will create a deviceUID, which you receive as part of the register device response. You will have to save this value and use it to create requests.

Like described here: https://github.com/OSGP/Documentation/issues/277#issuecomment-1187175916

> The unique device identification is a base 64 encoded string (something like this for example 'dGVzdDEyMzQ1Njc4') and is not the same as the simple device identification like 'SSLD_000-00-01'.

**Comment by scordedda** [comment]
Thank you for your support @kevinsmeets
