### ISSUE TITLE
Issue with starting Tomcat

### ISSUE THREAD

**Issue by RhitaB** [OSGP/Documentation#278]
Hello,
I've contacted you by email last week about starting Tomcat server. I've tried the tips you sent me back but I still can't get Tomcat to start. Here are the last messages it sends back on the console :

` [2022-07-20 14:15:00.013] [dev-box] [WsCoreQuartzScheduler_Worker-1] INFO o.o.a.w.s.s.ResendNotificationJob@execute:29 - Quartz triggered resend notification.`
`[2022-07-20 14:15:00.013] [dev-box] [TariffSwitchingQuartzScheduler_Worker-1] INFO o.o.a.w.s.s.ResponseDataCleanupJob@execute:29 - Quartz triggered cleanup of response data.`
`[2022-07-20 14:15:00.013] [dev-box] [CoreQuartzScheduler_Worker-1] INFO o.o.c.a.t.ScheduledTaskExecutorJob@execute:28 - Quartz triggered processing of scheduled task execution.`
`[2022-07-20 14:15:00.016] [dev-box] [PublicLightingQuartzScheduler_Worker-2] INFO o.o.a.w.s.s.ResendNotificationJob@execute:29 - Quartz triggered resend notification.`
`[2022-07-20 14:15:00.021] [dev-box] [WsCoreQuartzScheduler_Worker-2] INFO o.o.a.w.s.s.ResponseDataCleanupJob@execute:29 - Quartz triggered cleanup of response data.`
`[2022-07-20 14:15:00.029] [dev-box] [PublicLightingQuartzScheduler_Worker-1] INFO o.o.a.w.s.s.ResponseDataCleanupJob@execute:29 - Quartz triggered cleanup of response data.`
`[2022-07-20 14:15:00.030] [dev-box] [DistributionAutomationQuartzScheduler_Worker-1] INFO o.o.a.w.s.s.ResendNotificationJob@execute:29 - Quartz triggered resend notification.`
`[2022-07-20 14:15:00.036] [dev-box] [WsCoreQuartzScheduler_Worker-2] INFO o.o.a.w.c.a.s.ResponseUrlDataCleanupJob@execute:30 - Quartz triggered cleanup of response url data.`
`[2022-07-20 14:15:00.039] [dev-box] [SmartMeteringQuartzScheduler_Worker-2] INFO o.o.a.w.s.a.s.ResponseUrlDataCleanupJob@execute:29 - Quartz triggered cleanup of response url data.`
`[2022-07-20 14:15:00.044] [dev-box] [TariffSwitchingQuartzScheduler_Worker-2] INFO o.o.a.w.s.s.ResendNotificationJob@execute:29 - Quartz triggered resend notification.`
`[2022-07-20 14:15:00.053] [dev-box] [SmartMeteringQuartzScheduler_Worker-1] INFO o.o.a.w.s.s.ResendNotificationJob@execute:29 - Quartz triggered resend notification. `

Thank you for your help !

**Comment by kevinsmeets** [comment]
Hello @RhitaB ,

this logging looks OT. These are scheduled tasks that are performing some actions. There are no errors.

**Comment by RhitaB** [comment]
Hello,
What could then be the problem if these messages keep going but Tomcat isn't starting even after an hour ?

**Comment by kevinsmeets** [comment]
So, you do not see a logging line `Server startup in [xyz] milliseconds` like this example?
![image](https://user-images.githubusercontent.com/11557950/180216833-c6a20724-f9d6-4fb1-982d-8113e20c79cc.png)

If Tomcat is really not able to start within the number of seconds as configured here:
![image](https://user-images.githubusercontent.com/11557950/180217660-2639d7bc-a3e6-44bd-a825-dae814d7ab2e.png)

an error message will be shown (I set the timeout to 6 seconds to get the error fast):
![image](https://user-images.githubusercontent.com/11557950/180218056-382c3674-311d-4477-b8df-32c6a361b662.png)

Perhaps you will need to increase the amount of logging kept in the console. Right-click on the console, select preferences and set a large number for the `Console buffer size`:
![image](https://user-images.githubusercontent.com/11557950/180218600-ac2de993-1b2f-4c62-a0be-c0004dc47c5f.png)

**Comment by RhitaB** [comment]
Hello,

No I don't see the server startup line even after setting the timeout start time to 2400 seconds.
And yes I have set the Console buffer size to 1000000.

**Comment by kevinsmeets** [comment]
Hi @RhitaB ,

what is the result if you start one component, like `osgp-core`?

You can look at the folder `/var/log/osp/logs` which contains a log file per component.
Maybe one of the components is not able to fully start.
Search for errors or exceptions using something like `grep -i exception`.
