### ISSUE TITLE
Broken link in README.md 

### ISSUE THREAD

**Issue by Jonasvdbo** [OSGP/Documentation#281]
In https://github.com/OSGP/open-smart-grid-platform/blob/development/README.md the link to GXF wiki contact page seems to be broken:

![image](https://user-images.githubusercontent.com/3628277/188082740-35b1354d-1985-4265-8b43-7270e0267ed4.png)

![image](https://user-images.githubusercontent.com/3628277/188082773-05aff7af-bab7-4d09-a8b9-047c982055ee.png)

**Comment by kevinsmeets** [comment]
@Jonasvdbo links have been updated.
