### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Jonasvdbo** [OSGP/Documentation#282]
In https://github.com/OSGP/open-smart-grid-platform/blob/development/CONTRIBUTING.md the linkd to documentation guidelines, developer tools and more detailed contribution guidelines seems to be broken:

![image](https://user-images.githubusercontent.com/3628277/188083033-8afe7558-f482-4b31-a2f3-3c7a458d3085.png)

![image](https://user-images.githubusercontent.com/3628277/188083068-e642acb1-5a1e-4e29-b105-e0d3b06a9f13.png)

**Comment by kevinsmeets** [comment]
@Jonasvdbo links have been updated.
