### ISSUE TITLE
SQL error on inserting test-org organisation.

### ISSUE THREAD

**Issue by WalterBorgstein** [OSGP/Documentation#29]
Following the installation script from https://github.com/OSGP/Config I have to execute the following command.
run the script (/home/dev/Sources/Config/sql/create-test-org.sql) to insert 'test-org' organization into the organisation table of the osgp_core database.
The command can be found in the screenshot in installation script (http://54.77.62.182/documentation/chapter3/section3.html)

psql -U osp_admin -d osgp_core -f /home/dev/Sources/Config/sql/create-test-org.sql 

**The following error occures.**

dev@dev-box:~$ psql -U osp_admin -d osgp_core -f /home/dev/Sources/Config/sql/create-test-org.sql 
psql:/home/dev/Sources/Config/sql/create-test-org.sql:4: ERROR:  relation "organisation" does not exist
LINE 1: INSERT INTO organisation(id, creation_time, modification_tim...
                    ^

**Comment by kevinsmeets** [comment]
Short version: As described in our documentation (http://54.77.62.182/documentation/chapter3/section3.html) and in the README.md (https://github.com/OSGP/Config) developers are supposed to start Apache Tomcat before trying to insert the 'test-org' organization into the database.

Long version: We use FlyWay. This is a database migration tool. The database is provisioned (tables, sequences, etc. are created) when our software is started for the first time. This means when our wars get deployed to tomcat and tomcat is started, lot's of database migration is exectued. After that initial run, the organisation table in osgp-core database should exist.

The last 4 steps of the 'Manual steps' section show this:

- continue with starting Apache ActiveMQ (the executable can be found in the folder /home/dev/Downloads/apache-activemq-*/bin/linux-x86-64): by opening a terminal and use the command: sudo ./activemq console to start ActiveMQ as a terminal process (this way, ActiveMQ doesn't detach from the terminal and starts running as a daemon)

- with ActiveMQ running, the Tomcat7 server can be started

- open pgAdminIII and configure a connection: choose the 'Add a connection to a server.' and fill out the fields using Host localhost, Port 5432, Username osp_admin and Password 1234

- run the script (/home/dev/Sources/Config/sql/create-test-org.sql) to insert 'test-org' organization into the organisation table of the osgp_core database



@WalterBorgstein are you sure you started tomcat? dit that step succeed?

**Comment by WalterBorgstein** [comment]
![virtualbox_ubuntu 14 04 2 amd64 poging 2_16_02_2016_16_55_27](https://cloud.githubusercontent.com/assets/15366175/13081721/2db40cc8-d4ce-11e5-80b1-822c36ebf270.png)

Yep, did that. See the screenshot for all the related items. Tomcat is starte, Active MQ.

**Comment by kevinsmeets** [comment]
Have all components of the software started up without errors. (this can be seen in the console of eclipse)?

**Comment by WalterBorgstein** [comment]
I will restart the steps from the starting of Eclipse/Tomcat/Active MQ.
This is the log of eclipse.


org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/dev/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.5.1.20150109-1820.xml
org.eclipse.m2e.logback.configuration: Initializing logback
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
dev@dev-box:~/Downloads/eclipse$ ./eclipse --clean
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/dev/workspace2/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.5.1.20150109-1820.xml
org.eclipse.m2e.logback.configuration: Initializing logback
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
dev@dev-box:~/Downloads/eclipse$ ./eclipse --clean
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/dev/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.5.1.20150109-1820.xml
org.eclipse.m2e.logback.configuration: Initializing logback
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
d

**Comment by kevinsmeets** [comment]
That is not the logging of the applications that have started. 
That is the logging of the startup of Eclipse (why don't you start eclipse by clicking on the executable instead of starting in from a terminal?)

In Eclipse there's a screen that is calle dConsole. There the applications print logging during startup.

**Comment by WalterBorgstein** [comment]
Thanks. Will do! I will verify if and where I made an error and make a
suggestion to improve the process.

**Comment by WalterBorgstein** [comment]
I checked the 

- installation of Tomcat, 
- ActiveMQ,
- Creating Sym Link to Maven Settings
- Usage of the Context.xml
(added a <!DOCTYPE xml> in line 2 to prevent validate error)

The Tomcat console has a lot of error in them. I can't figure out what they relate to. Maybe you can see it right away?

[Start tomcat log.txt](https://github.com/OSGP/Documentation/files/133912/Start.tomcat.log.txt)

[Tomcat log.txt](https://github.com/OSGP/Documentation/files/133897/Tomcat.log.txt)

**Comment by kevinsmeets** [comment]
In the logging I see that most components fail to start.
@rlemmers Can you check and if needed sync the configuration files in https://github.com/OSGP/Config ?

**Comment by Sander3003** [comment]
My tomcat server also shows errors when it wants to boot: 
![screenshot from 2016-02-21 16 01 10](https://cloud.githubusercontent.com/assets/7427358/13203265/c0515088-d8b4-11e5-874a-07f09eae4b73.png)

**Comment by Sander3003** [comment]
I tried it yesterday and I still experienced (probably) this problem. Maybe we can make the installation more easy. Example of openhab: https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/ide.md . The configure Eclipse with a script.

**Comment by Sander3003** [comment]
The Vagrant installation script should work now: http://documentation.opensmartgridplatform.org/Userguide/Installation/Setup-VM-Vagrant.html

**Comment by kolawoletech** [comment]
I am having the exact same after following the instructions using Vagrant

**Comment by kevinsmeets** [comment]
@kolawoletech If you run into `ERROR: relation "organisation" does not exist` the most likely cause is that the tables have not been created yet. 

The tables are created by starting the components. We are using [Flyway](https://flywaydb.org/) to migrate the databases. 

- This migration script creates the table: https://github.com/OSGP/open-smart-grid-platform/blob/development/osgp/platform/osgp-core/src/main/resources/db/migration/V2014.001__Initial_version_PostgreSQL.sql
- The component `osgp-core` contains this script
- Try starting component in Tomcat and the table should be created

**Comment by kolawoletech** [comment]
Okay, I got it to work eventually but i still have  couple of issues. On setting the project on SoapUI, I cant viewe the UI of the projects at https://localhost/web-device-simulator/devices or at any url, I get a 404 error saying 

Type Status Report

Message /web-device-simulator/devices

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists

**Comment by kevinsmeets** [comment]
The error you describe indicates the `web-device-simulator` component is not available in your Tomcat application server.
- has the component been deployed to Tomcat?
- are there errors in the logging when the component starts in Tomcat?

**Comment by kolawoletech** [comment]
There are a bunch of things that are off but I have found a way, I am
documenting them and let you know where the issues arose for me. I have
been looking at issues from past releases and adjusting accordingly, for
instance, I use the local tomcat installation instead of the metadata
version on the server creation side for things to work in accordance with
the documentation. I also had issues with the SSL version of the web demos
and had to restart apache for it to register the SSL test-org


[image: --]
kolawole Olulana
[image: http://]about.me/kolawole
*+27620294056 *
