### ISSUE TITLE
What is the internal datamodel in the open smart grid platform?

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#49]
This topic should be in the documentation.

**Comment by Sander3003** [comment]
This can be generated.

**Comment by Sander3003** [comment]
If it is generate via e.g. Jenkins and published somewhere else. The documentation can point to that location.

**Comment by WalterBorgstein** [comment]
This has recently been generated by Sander on behalf of Alliander.
Check the following files for OSGP-core-datamodel, osgp-protocol-adapter and osgp-logging.
![osgp-core-datamodel](https://cloud.githubusercontent.com/assets/15366175/15420630/27bbbb60-1e6e-11e6-8cd1-b300c2abed24.png)
![osgp-protocol-adapter-oslp](https://cloud.githubusercontent.com/assets/15366175/15420635/3074862e-1e6e-11e6-8a35-e614e2fc7edd.png)
![osgp-logging](https://cloud.githubusercontent.com/assets/15366175/15420643/3851b236-1e6e-11e6-9f77-988ceeb4eec0.png)

**Comment by Sander3003** [comment]
Nice, Can you add it to the gitbook?

**Comment by WalterBorgstein** [comment]
I'll do this on Tuesday.

**Comment by Sander3003** [comment]
Is this fixed now?

**Comment by WalterBorgstein** [comment]
No. Scheduled for friday.

**Comment by Sander3003** [comment]
This is the data model used in the OSGP core services layer and should be added to documentation related to this layer.

**Comment by Sander3003** [comment]
Fixed: http://54.77.62.182/documentation/Architecture/Platform-components-description.html
Thanks @WalterBorgstein for your input
