### ISSUE TITLE
Open smart grid platform experience

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#75]
We are planning to improve the open smart grid platform documentation and installation to make the open smart grid platform experience better.

@ganeshsrvnn Can you tell about your open smart grid platform experience and improvement suggestions?

**Comment by Sander3003** [comment]
@edwinmat Can you tell about your open smart grid platform experience and improvement suggestions?

**Comment by ganeshsrvnn** [comment]
Hello,

My feedback below,

1. The documentation elaborates developer setup , I would suggest for
standalone deployment steps of the platform other than from developer
perspective. How to build and deploy without eclipse setup?
2. User Management:Missing WSDL for web-api-user-management web service,
how to create new user?. API description for user management shall be added.
3. Keystore creation steps for a new organisation
4. Steps for a developer to integrate new protocol adapter into the
platform.
5. Guidelines for web application development using the platform.

Hope it helps. :)

regards,
Saravanan G

**Comment by edwinmat** [comment]
I've only tried once and did not succeed in the installation. I've sent my reaction to Jeffrey. The problem was that following the documentation resulted in many errors. I suggested to provide a VM with a working OSGP instance to ease testing and experimentation.

**Comment by Sander3003** [comment]
Thank you both for your input! We will put your feedback on the roadmap and take it into consideration for the upcomming documentation development. @ganeshsrvnn maybe we setup an call? we like to know how we can support you. We want to make this project an true open source community driven project with multiple partners. Contact me sander.jansen (#@#) alliander.com

**Comment by Sander3003** [comment]
@pczeeuw made major improvements to fix address the concerns in this issue. An easy (test) installation can be done via a Vagrant script and the documentation has some big updates.  File an new issue if you find new improvement options. http://documentation.opensmartgridplatform.org
