### ISSUE TITLE
Are the PDF and Epub version also available?

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#9]
I can only find the HTML version on the build server.

**Comment by kevinsmeets** [comment]
No those version are not build. Actually, I had a problem with the plugin that is needed to build these other file types.

**Comment by Sander3003** [comment]
We should fix this when we have time to do so.

**Comment by Sander3003** [comment]
Is this fixed or did you move this topic to Jira?

**Comment by kevinsmeets** [comment]
Moved to JIRA

Kevin Smeets | Experienced Software Engineer,
Application Services | CGI
Stationstraat 49, 6411 NK Heerlen, Nederland
T: +31 88 564 4005 | M: +31 6 5060 5292
kevin.smeets@cgi.com<mailto:kevin.smeets@cgi.com> | www.cgi.com<http://www.cgi.com/> | www.cginederland.nl<http://www.cginederland.nl>

Volg CGI Nederland op: LinkedIn<http://www.linkedin.com/company/cgi-in-nederland> | Twitter<http://twitter.com/CGI_NL> | Facebook<http://facebook.com/CGINederland> | YouTube<http://www.youtube.com/user/CGINederland>
CGI Nederland B.V., registered office in Amstelveen, The Netherlands
Registration Number Chamber of Commerce: 33136004
[cgi-logo-email-45x25]

P Save a tree. Don't print this e-mail unless it's really necessary~

CONFIDENTIALITY NOTICE: Proprietary/Confidential Information belonging to CGI Group Inc. and its affiliates may be contained in this message. If you are not a recipient indicated or intended in this message (or responsible for delivery of this message to such person), or you think for any reason that this message may have been addressed to you in error, you may not use or copy or deliver this message to anyone else. In such case, you should destroy this message and are asked to notify the sender by reply e-mail.
